version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: gestioncontenido-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: retochimba_db
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: password123
    volumes:
      - gestioncontenido_postgres_data:/var/lib/postgresql/data
    networks:
      - gestioncontenido-network

  backend:
    container_name: gestioncontenido-backend
    build:
      context: .
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - gestioncontenido-network

volumes:
  gestioncontenido_postgres_data:

networks:
  gestioncontenido-network:
    driver: bridge
