version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: gestioncontenido-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: gestion_contenido
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
